// PDF generation using jsPDF via dynamic import-free approach
// We generate a clean HTML page and return it for the browser to print-to-PDF
// This works without any native dependencies on Vercel

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end();

  const { letter } = req.body;
  if (!letter) return res.status(400).json({ error: 'No letter provided' });

  // Return a clean print-ready HTML page
  // The browser renders it and the user saves as PDF
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>DepositBack — Demand Letter</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,600;1,400&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'EB Garamond', Georgia, serif;
      font-size: 13pt;
      line-height: 1.85;
      color: #1a1a2e;
      background: #fff;
      padding: 0;
    }
    .page {
      max-width: 720px;
      margin: 0 auto;
      padding: 72px 64px;
      min-height: 100vh;
    }
    .letterhead {
      border-bottom: 2px solid #1a2a5e;
      padding-bottom: 20px;
      margin-bottom: 36px;
      display: flex;
      justify-content: space-between;
      align-items: flex-end;
    }
    .brand {
      font-size: 22pt;
      font-weight: 600;
      color: #1a2a5e;
      letter-spacing: -0.5px;
    }
    .brand span { color: #2a6abf; }
    .tagline { font-size: 9pt; color: #888; letter-spacing: 1px; text-transform: uppercase; }
    .letter-body {
      white-space: pre-wrap;
      font-size: 12pt;
      line-height: 1.9;
      color: #1a1a1a;
    }
    .footer {
      margin-top: 48px;
      padding-top: 16px;
      border-top: 1px solid #ddd;
      font-size: 8pt;
      color: #aaa;
      text-align: center;
    }
    @media print {
      body { padding: 0; }
      .page { padding: 48px 52px; }
      .no-print { display: none; }
      @page { margin: 0; size: letter; }
    }
  </style>
</head>
<body>
  <div class="page">
    <div class="letterhead">
      <div>
        <div class="brand">Deposit<span>Back</span></div>
        <div class="tagline">Tenant Rights · AI-Powered</div>
      </div>
      <div style="text-align:right;font-size:9pt;color:#888;">depositback.ca</div>
    </div>
    <div class="letter-body">${letter.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}</div>
    <div class="footer">Generated by DepositBack · depositback.ca · For informational purposes only — not legal advice</div>
  </div>

  <script>
    window.onload = function() { window.print(); }
  </script>
</body>
</html>`;

  res.setHeader('Content-Type', 'text/html');
  res.send(html);
}
