import { Resend } from 'resend';
import { Document, Packer, Paragraph, TextRun, AlignmentType } from 'docx';
import PDFDocument from 'pdfkit';

const resend = new Resend(process.env.RESEND_API_KEY);

async function generateDocx(letterText) {
  const paragraphs = letterText.split('\n').map(line => {
    return new Paragraph({
      alignment: AlignmentType.LEFT,
      children: [new TextRun({ text: line.trim(), font: 'Times New Roman', size: 24 })],
      spacing: { after: line.trim() ? 120 : 60 },
    });
  });

  const doc = new Document({
    sections: [{
      properties: { page: { margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
      children: [
        new Paragraph({
          children: [
            new TextRun({ text: 'Deposit', font: 'Times New Roman', size: 36, bold: true, color: '1a2a5e' }),
            new TextRun({ text: 'Back', font: 'Times New Roman', size: 36, bold: true, color: '2a6abf' }),
          ],
          spacing: { after: 240 },
          border: { bottom: { color: '1a2a5e', size: 6, space: 6, style: 'single' } },
        }),
        ...paragraphs,
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: 'Generated by DepositBack · depositback.ca · For informational purposes only', font: 'Times New Roman', size: 16, color: 'aaaaaa', italics: true })],
          spacing: { before: 480 },
        }),
      ],
    }],
  });

  return await Packer.toBuffer(doc);
}

function generatePdf(letterText) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ margin: 72, size: 'LETTER' });

    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.font('Times-Bold').fontSize(18).fillColor('#1a2a5e').text('Deposit', 72, 52, { continued: true });
    doc.fillColor('#2a6abf').text('Back');
    doc.moveTo(72, 68).lineTo(doc.page.width - 72, 68).strokeColor('#1a2a5e').lineWidth(1.5).stroke();

    // Body
    doc.font('Times-Roman').fontSize(11).fillColor('#1a1a1a').moveDown(1);
    letterText.split('\n').forEach(line => {
      if (line.trim() === '') {
        doc.moveDown(0.5);
      } else {
        doc.text(line.trim(), { width: doc.page.width - 144, lineGap: 4 });
      }
    });

    // Footer
    doc.font('Times-Roman').fontSize(8).fillColor('#aaaaaa')
      .text(
        'Generated by DepositBack · depositback.ca · For informational purposes only',
        72, doc.page.height - 40,
        { align: 'center', width: doc.page.width - 144 }
      );

    doc.end();
  });
}

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { email, letter, tenantName, province } = req.body;
  if (!email || !letter) return res.status(400).json({ error: 'Missing email or letter' });

  const provinceNames = { ON: 'Ontario', BC: 'British Columbia', AB: 'Alberta', QC: 'Quebec', MB: 'Manitoba', SK: 'Saskatchewan', NS: 'Nova Scotia', NB: 'New Brunswick', NL: 'Newfoundland', PE: 'PEI' };
  const provinceName = provinceNames[province] || 'Canada';
  const firstName = tenantName ? tenantName.split(' ')[0] : 'there';

  const letterHtml = letter.split('\n')
    .map(line => line.trim() ? `<p style="margin:0 0 6px;font-size:13px;font-family:'Times New Roman',serif;color:#1a1a1a;line-height:1.7;">${line.trim()}</p>` : '<br>')
    .join('');

  try {
    const [docxBuffer, pdfBuffer] = await Promise.all([
      generateDocx(letter),
      generatePdf(letter),
    ]);

    await resend.emails.send({
      from: 'DepositBack <letters@melomaniacstudios.com>',
      to: email,
      subject: 'Your Demand Letter is Ready — DepositBack',
      html: `
        <div style="font-family:-apple-system,sans-serif;max-width:600px;margin:0 auto;padding:40px 24px;background:#ffffff;">
          <div style="margin-bottom:28px;">
            <span style="font-size:22px;font-weight:700;color:#1a2a5e;">Deposit</span><span style="font-size:22px;font-weight:700;color:#2a6abf;">Back</span>
          </div>
          <h1 style="font-size:20px;font-weight:700;color:#0f172a;margin:0 0 12px;">Your demand letter is ready, ${firstName}.</h1>
          <p style="font-size:14px;color:#475569;line-height:1.6;margin:0 0 24px;">
            Your ${provinceName} tenant demand letter is attached in two formats — <strong>PDF</strong> and <strong>Word (.docx)</strong> — so you have it no matter what device you're on.
          </p>

          <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:20px 24px;margin-bottom:28px;">
            <div style="font-size:12px;font-weight:700;color:#0f172a;margin-bottom:12px;text-transform:uppercase;letter-spacing:0.05em;">What to do next</div>
            <div style="font-size:13px;color:#475569;line-height:1.8;">
              <div>→ <strong>Email the letter to your landlord</strong> — creates a timestamped paper trail</div>
              <div>→ <strong>CC yourself</strong> so you have proof it was sent</div>
              <div>→ <strong>Follow up in 7 days</strong> if no response</div>
              <div>→ <strong>Ignored after 14 days?</strong> File with your provincial tribunal — free to do</div>
            </div>
          </div>

          <div style="border:1px solid #e2e8f0;border-radius:10px;padding:28px 32px;margin-bottom:28px;background:#fafafa;">
            <div style="font-size:11px;font-weight:700;color:#94a3b8;text-transform:uppercase;letter-spacing:0.08em;margin-bottom:16px;">Your Letter</div>
            ${letterHtml}
          </div>

          <p style="font-size:12px;color:#94a3b8;line-height:1.6;border-top:1px solid #e2e8f0;padding-top:20px;margin:0;">
            For informational purposes only — not legal advice.<br>
            <a href="https://depositback.ca" style="color:#2a6abf;">depositback.ca</a>
          </p>
        </div>
      `,
      attachments: [
        {
          filename: 'DepositBack-Demand-Letter.pdf',
          content: pdfBuffer.toString('base64'),
          contentType: 'application/pdf',
        },
        {
          filename: 'DepositBack-Demand-Letter.docx',
          content: docxBuffer.toString('base64'),
          contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        },
      ],
    });

    return res.status(200).json({ success: true });
  } catch (err) {
    console.error('Email error:', err);
    return res.status(500).json({ error: 'Failed to send email' });
  }
}
