import { Resend } from 'resend';
import { Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel } from 'docx';
import PDFDocument from 'pdfkit';

const resend = new Resend(process.env.RESEND_API_KEY);

// Generate DOCX buffer from letter text
async function generateDocx(letterText, tenantName) {
  const lines = letterText.split('\n');

  const paragraphs = lines.map((line, i) => {
    const trimmed = line.trim();

    // Blank line = spacer paragraph
    if (!trimmed) {
      return new Paragraph({ children: [new TextRun({ text: '', break: 1 })] });
    }

    // First non-empty line = treat as date/header
    const isHeader = i < 5 && trimmed.length < 60 && !trimmed.includes(' ');

    return new Paragraph({
      alignment: AlignmentType.LEFT,
      children: [
        new TextRun({
          text: trimmed,
          font: 'Times New Roman',
          size: 24, // 12pt
          bold: isHeader,
        }),
      ],
      spacing: { after: 120 },
    });
  });

  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 }, // 1 inch margins
          },
        },
        children: [
          new Paragraph({
            alignment: AlignmentType.LEFT,
            children: [
              new TextRun({ text: 'Deposit', font: 'Times New Roman', size: 36, bold: true, color: '1a2a5e' }),
              new TextRun({ text: 'Back', font: 'Times New Roman', size: 36, bold: true, color: '2a6abf' }),
            ],
            spacing: { after: 240 },
            border: { bottom: { color: '1a2a5e', size: 6, space: 6, style: 'single' } },
          }),
          ...paragraphs,
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: 'Generated by DepositBack · depositback.ca · For informational purposes only',
                font: 'Times New Roman',
                size: 16,
                color: 'aaaaaa',
                italics: true,
              }),
            ],
            spacing: { before: 480 },
          }),
        ],
      },
    ],
  });

  return await Packer.toBuffer(doc);
}

// Generate PDF buffer from letter text
function generatePdf(letterText) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ margin: 72, size: 'LETTER' });

    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.font('Times-Bold').fontSize(18).fillColor('#1a2a5e').text('Deposit', 72, 52, { continued: true });
    doc.fillColor('#2a6abf').text('Back');
    doc.moveTo(72, 68).lineTo(doc.page.width - 72, 68).strokeColor('#1a2a5e').lineWidth(1.5).stroke();

    // Body
    doc.font('Times-Roman').fontSize(11).fillColor('#1a1a1a').moveDown(1);
    const lines = letterText.split('\n');
    lines.forEach(line => {
      if (line.trim() === '') {
        doc.moveDown(0.5);
      } else {
        doc.text(line.trim(), { width: doc.page.width - 144, lineGap: 4 });
      }
    });

    // Footer
    doc.font('Times-Roman').fontSize(8).fillColor('#aaaaaa')
      .text(
        'Generated by DepositBack · depositback.ca · For informational purposes only',
        72,
        doc.page.height - 40,
        { align: 'center', width: doc.page.width - 144 }
      );

    doc.end();
  });
}

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { email, letter, tenantName, province } = req.body;

  if (!email || !letter) {
    return res.status(400).json({ error: 'Missing email or letter' });
  }

  try {
    // Generate both file formats in parallel
    const [docxBuffer, pdfBuffer] = await Promise.all([
      generateDocx(letter, tenantName),
      generatePdf(letter),
    ]);

    const provinceNames = {
      ON: 'Ontario', BC: 'British Columbia', AB: 'Alberta', QC: 'Quebec',
      MB: 'Manitoba', SK: 'Saskatchewan', NS: 'Nova Scotia',
      NB: 'New Brunswick', NL: 'Newfoundland', PE: 'PEI',
    };
    const provinceName = provinceNames[province] || 'Canada';

    await resend.emails.send({
      from: 'DepositBack <letters@depositback.ca>',
      to: email,
      subject: `Your Demand Letter is Ready — DepositBack`,
      html: `
        <div style="font-family: -apple-system, sans-serif; max-width: 560px; margin: 0 auto; padding: 40px 24px; background: #ffffff;">
          <div style="margin-bottom: 32px;">
            <span style="font-size: 22px; font-weight: 700; color: #1a2a5e;">Deposit</span><span style="font-size: 22px; font-weight: 700; color: #2a6abf;">Back</span>
          </div>
          <h1 style="font-size: 22px; font-weight: 700; color: #0f172a; margin: 0 0 12px;">Your demand letter is attached.</h1>
          <p style="font-size: 15px; color: #475569; line-height: 1.6; margin: 0 0 24px;">
            Hi ${tenantName ? tenantName.split(' ')[0] : 'there'},<br><br>
            Your ${provinceName} tenant demand letter is attached to this email in two formats — PDF and Word (.docx) — so you have it no matter what device or app you use to send it.
          </p>

          <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 20px 24px; margin-bottom: 28px;">
            <div style="font-size: 13px; font-weight: 700; color: #0f172a; margin-bottom: 12px; text-transform: uppercase; letter-spacing: 0.05em;">What to do next</div>
            <div style="font-size: 14px; color: #475569; line-height: 1.7;">
              <div style="margin-bottom: 8px;">→ <strong>Email it to your landlord</strong> — creates a timestamped paper trail</div>
              <div style="margin-bottom: 8px;">→ <strong>CC yourself</strong> so you have proof it was sent</div>
              <div style="margin-bottom: 8px;">→ <strong>Follow up in 7 days</strong> if no response</div>
              <div>→ <strong>If ignored after 14 days</strong> — file with your provincial tribunal (free)</div>
            </div>
          </div>

          <p style="font-size: 13px; color: #94a3b8; line-height: 1.6; border-top: 1px solid #e2e8f0; padding-top: 20px; margin: 0;">
            For informational purposes only — not legal advice.<br>
            <a href="https://depositback.ca" style="color: #2a6abf;">depositback.ca</a>
          </p>
        </div>
      `,
      attachments: [
        {
          filename: 'DepositBack-Demand-Letter.pdf',
          content: pdfBuffer.toString('base64'),
          contentType: 'application/pdf',
        },
        {
          filename: 'DepositBack-Demand-Letter.docx',
          content: docxBuffer.toString('base64'),
          contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        },
      ],
    });

    return res.status(200).json({ success: true });
  } catch (err) {
    console.error('Email send error:', err);
    return res.status(500).json({ error: 'Failed to send email' });
  }
}
